export const GET_RESULTS_SUCCESS = "GET_RESULTS_SUCCESS";
export const GET_ADVANCED_RESULTS_SUCCESS = "GET_ADVANCED_RESULTS_SUCCESS";
export const READ_MAIL_SUCCESS = "READ_MAIL_SUCCESS";
export const GET_INITIAL_SEARCH_STATE = "GET_INITIAL_SEARCH_STATE";