export const enronEvents = [
    { date: "1985", text: "Houston Natural Gas merges with InterNorth to form Enron, a natural gas pipeline company with 37,000 miles of pipe." },
    { date: "1989", text: "Enron begins trading natural gas commodities." },
    { date: "1998", text: "Fastow becomes CFO." },
    { date: "Dec. 1996", text: "Jeff Skilling becomes Enron's president and COO." },
    { date: "Aug. 2000", text: "Enron shares hits all-time high $90.56." },
    { date: "Aug. 14, 2001", text: "Skilling resigns due to personal reasons only after six months as president. Ken Lay returns as CEO again." },
    { date: "Aug. 15, 2001", text: "Vice president Sherron Watkins expresses concern about Enron's questionable accounting practices." },
    { date: "Oct. 16, 2001", text: "Enron reports a $638 million loss along with a $1.2 billion reduction in shareholder equity." },
    { date: "Oct. 22, 2001", text: "Enron acknowledges SEC inquiry of the possible conflict of interest between Enron and its' partnerships. Enron shares drop." },
    { date: "Oct. 24, 2001", text: "Enron releases Fastow." },
    { date: "Nov. 9, 2001", text: "Dynegy agrees to acquire Enron for $9 bilion." },
    { date: "Nov. 19, 2001", text: "Enron restates its third-quarter earnings and discloses it is trying to restructure a $690 million obligation that could come due Nov. 27." },
    { date: "Nov. 29, 2001", text: "Dynegy backs out of aquisition deal." },
    { date: "Dec. 2, 2001", text: "Enron files for Chapter 11." },
    { date: "Dec. 3, 2001", text: "4,000 Enron employees laid off." },
    { date: "Jan. 9, 2002", text: "Justice Department begins criminal investigation of Enron." },
    { date: "Jan. 10, 2002", text: "Arthur Andersen announces the disposal of Enron documents by employees." },
    { date: "Jan. 24, 2002", text: "Lay resigns and is replaced by Stephen Cooper as CEO." },
    { date: "Jan. 25, 2002", text: "Cliff Baxter dies from a suicide gunshot to the head." },
    { date: "Mar. 14, 2002", text: "Arthur Andersen indicted for obstruction of justice for destroying Enron-related documents." },
    { date: "Aug. 31, 2002", text: "Arthur Andersen surrenders licence to practice in US. 85,000 people lose their jobs." },
    { date: "Oct. 31, 2002", text: "Fastow indicted on 78 charges of conspiracy, fraud, money laundering and other counts." },
    { date: "May 1, 2003", text: "Fastow's wife Lea along with seven former Enron executives charged with conspiracy and filing false tax forms." },
    { date: "Jan. 14, 2004", text: "Andrew and Lea Fastow plead guilty. Fastow agrees to serve 10 years in prison and forfeit $23.8 million." },
    { date: "Feb. 19, 2004", text: "Skilling pleads not guilty to 35 counts of wire and securities fraud, conspiracy and insider traiding." },
    { date: "July 8, 2004", text: "Lay is indicted on 11 counts of fraud and surrenders to the FBI." },
    { date: "Jan. 7, 2005", text: "US supreme court agrees to consider overturning Arthur Andersen conviction." },
    { date: "Jan. 30, 2005", text: "Trial begins in Houston, TX for Lay and Skilling." },
    { date: "May 25, 2006", text: "Skilling is to serve 24 years and 4 months forfeiting $45 million. Ken Lay dies before sentencing." },
    { date: "Sep. 26, 2006", text: "Fastow gets 6 years." }
];